export const ADD_PRODUCT_TO_BASKET = 'basket/ADD_PRODUCT_TO_BASKET';
export const DELETE_PRODUCT_FROM_BASKET = 'basket/DELETE_PRODUCT_FROM_BASKET';
export const CHANGE_PRODUCT_COUNT = 'basket/CHANGE_PRODUCT_COUNT';
export const CLEAR_BASKET = 'basket/CLEAR_BASKET';
