export const data = [
  {
    id: 1,
    name: 'Винегрет овощной',
    price: '40',
    calorie: '550',
    category: 'Салаты',
    description:
      'Свекла, морковь, картофель, капуста, зеленый горошек, масло растительное',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 2,
    name: 'Нарезка из свежих овощей',
    price: '55',
    calorie: '550',
    category: 'Салаты',
    description: 'Огурец св., помидор св., перец болгарский',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 3,
    name: 'Окрошка мясная',
    price: '80',
    calorie: '550',
    category: 'Супы',
    description:
      'Квас, мясо говядины, огурец свежий, редис, зелень, картофель отварной, сметана',
    image: require('./../assets/img/salat.png'),
    gramm: '250/20',
  },
  {
    id: 4,
    name: 'Каша пшенная',
    price: '35',
    calorie: '550',
    category: 'Молочные блюда',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '200/10',
  },
  {
    id: 5,
    name: 'Говядина отварная',
    price: '120',
    calorie: '550',
    category: 'Горячее из мяса',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 6,
    name: 'Поджарка из курицы',
    price: '90',
    calorie: '550',
    category: 'Горячее из птицы',
    description:
      'Мясо бедра куриное обжареное с луком, морковью и болгарским перцем',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 7,
    name: 'Горбуша с помидорами',
    price: '110',
    calorie: '550',
    category: 'Горячее из рыбы',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '110',
  },
  {
    id: 8,
    name: 'Гречка отварная',
    price: '35',
    calorie: '550',
    category: 'Гарниры',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 9,
    name: 'Драник картофельный со сметаной',
    price: '35',
    calorie: '550',
    category: 'Гарниры',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 10,
    name: 'Блинчики со сгущеным молоком',
    price: '17',
    calorie: '550',
    category: 'Мучные изделия',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 11,
    name: 'Блин /фаршированный клубникой',
    price: '17',
    calorie: '550',
    category: 'Мучные изделия',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 12,
    name: 'Вода пит. Алтай Аква 0,5л. ПЭТ',
    price: '28',
    calorie: '550',
    category: 'Напитки и соки',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '500',
  },
  {
    id: 13,
    name: 'Варенье клубничное',
    price: '15',
    calorie: '550',
    category: 'Соусы',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '30',
  },
  {
    id: 14,
    name: 'Сметана',
    price: '7',
    calorie: '550',
    category: 'Соусы',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '20',
  },
  {
    id: 15,
    name: 'Вареники с клубникой и сливочным маслом',
    price: '60',
    calorie: '550',
    category: 'Пельмени и вареники',
    description: 'Тесто пельменное, клубника, сахар, масло сливочное',
    image: require('./../assets/img/salat.png'),
    gramm: '200/10',
  },
  {
    id: 16,
    name: 'Пельмени Домашние отварные с маслом',
    price: '95',
    calorie: '550',
    category: 'Пельмени и вареники',
    description:
      'Тесто пельменное, говядина, свинина, лук, масло сливочное, зелень.',
    image: require('./../assets/img/salat.png'),
    gramm: '200/10',
  },
  {
    id: 17,
    name: 'Яйцо отварное',
    price: '15',
    calorie: '550',
    category: 'Прочее',
    description:
      'Тесто пельменное, говядина, свинина, лук, масло сливочное, зелень.',
    image: require('./../assets/img/salat.png'),
    gramm: '50',
  },
  {
    id: 18,
    name: 'Пирожки с картофелем и сосисками',
    price: '30',
    calorie: '550',
    category: 'Пироги и торты',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '15',
  },
  {
    id: 19,
    name: 'Комплексный обед 12',
    price: '230',
    calorie: '550',
    category: 'Комплексный обед',
    description:
      'Суп куриный с клецками, пюре с мясной котлетой, салат из свежей капусты, напиток из облепихи',
    image: require('./../assets/img/salat.png'),
    gramm: '15',
  },
];
