export const data = [
  {
    id: 1,
    name: 'Винегрет овощной',
    price: '40',
    calorie: '550',
    category_id: 2,
    description:
      'Свекла, морковь, картофель, капуста, зеленый горошек, масло растительное',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 2,
    name: 'Нарезка из свежих овощей',
    price: '55',
    calorie: '550',
    category_id: 2,
    description: 'Огурец св., помидор св., перец болгарский',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 3,
    name: 'Окрошка мясная',
    price: '80',
    calorie: '550',
    category_id: 3,
    description:
      'Квас, мясо говядины, огурец свежий, редис, зелень, картофель отварной, сметана',
    image: require('./../assets/img/salat.png'),
    gramm: '250/20',
  },
  {
    id: 4,
    name: 'Каша пшенная',
    price: '35',
    calorie: '550',
    category_id: 'Молочные блюда',
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '200/10',
  },
  {
    id: 5,
    name: 'Говядина отварная',
    price: '120',
    calorie: '550',
    category_id: 4,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 6,
    name: 'Поджарка из курицы',
    price: '90',
    calorie: '550',
    category_id: 5,
    description:
      'Мясо бедра куриное обжареное с луком, морковью и болгарским перцем',
    image: require('./../assets/img/salat.png'),
    gramm: '100',
  },
  {
    id: 7,
    name: 'Горбуша с помидорами',
    price: '110',
    calorie: '550',
    category_id: 6,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '110',
  },
  {
    id: 8,
    name: 'Гречка отварная',
    price: '35',
    calorie: '550',
    category_id: 7,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 9,
    name: 'Драник картофельный со сметаной',
    price: '35',
    calorie: '550',
    category_id: 7,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 10,
    name: 'Блинчики со сгущеным молоком',
    price: '17',
    calorie: '550',
    category_id: 8,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 11,
    name: 'Блин /фаршированный клубникой',
    price: '17',
    calorie: '550',
    category_id: 8,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '150',
  },
  {
    id: 12,
    name: 'Вода пит. Алтай Аква 0,5л. ПЭТ',
    price: '28',
    calorie: '550',
    category_id: 9,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '500',
  },
  {
    id: 13,
    name: 'Варенье клубничное',
    price: '15',
    calorie: '550',
    category_id: 10,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '30',
  },
  {
    id: 14,
    name: 'Сметана',
    price: '7',
    calorie: '550',
    category_id: 10,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '20',
  },
  {
    id: 15,
    name: 'Вареники с клубникой и сливочным маслом',
    price: '60',
    calorie: '550',
    category_id: 11,
    description: 'Тесто пельменное, клубника, сахар, масло сливочное',
    image: require('./../assets/img/salat.png'),
    gramm: '200/10',
  },
  {
    id: 16,
    name: 'Пельмени Домашние отварные с маслом',
    price: '95',
    calorie: '550',
    category_id: 11,
    description:
      'Тесто пельменное, говядина, свинина, лук, масло сливочное, зелень.',
    image: require('./../assets/img/salat.png'),
    gramm: '200/10',
  },
  {
    id: 17,
    name: 'Яйцо отварное',
    price: '15',
    calorie: '550',
    category_id: 12,
    description:
      'Тесто пельменное, говядина, свинина, лук, масло сливочное, зелень.',
    image: require('./../assets/img/salat.png'),
    gramm: '50',
  },
  {
    id: 18,
    name: 'Пирожки с картофелем и сосисками',
    price: '30',
    calorie: '550',
    category_id: 13,
    description: '',
    image: require('./../assets/img/salat.png'),
    gramm: '15',
  },
  {
    id: 19,
    name: 'Комплексный обед 12',
    price: '230',
    calorie: '550',
    category_id: 1,
    description:
      'Суп куриный с клецками, пюре с мясной котлетой, салат из свежей капусты, напиток из облепихи',
    image: require('./../assets/img/salat.png'),
    gramm: '15',
  },
];

export const orders = [
  {
    id: 1,
    cost: 210,
    date_order: '2022-05-18',
    products: [
      {
        id: 1,
        name: 'Винегрет овощной',
        price: 230,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 2,
        name: 'Винегрет овощной',
        price: 225,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 3,
        name: 'Винегрет овощной',
        price: 202,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
    ],
  },
  {
    id: 2,
    cost: 212,
    date_order: '2022-05-19',
    products: [
      {
        id: 4,
        name: 'Винегрет овощной',
        date: '21.05.2022',
        price: 196,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 5,
        name: 'Винегрет овощной',
        date: '20.05.2022',
        price: 215,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
    ],
  },
  {
    id: 3,
    cost: 214,
    date_order: '2022-05-20',
    products: [
      {
        id: 1,
        name: 'Винегрет овощной',
        date: '24.05.2022',
        price: 230,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 2,
        name: 'Винегрет овощной',
        date: '23.05.2022',
        price: 225,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
    ],
  },
  {
    id: 4,
    cost: 230,
    date_order: '2022-05-21',
    products: [
      {
        id: 1,
        name: 'Винегрет овощной',
        date: '24.05.2022',
        price: 230,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 2,
        name: 'Винегрет овощной',
        date: '23.05.2022',
        price: 225,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
    ],
  },
  {
    id: 5,
    cost: 220,
    date_order: '2022-05-22',
    products: [
      {
        id: 1,
        name: 'Винегрет овощной',
        date: '24.05.2022',
        price: 230,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 2,
        name: 'Винегрет овощной',
        date: '23.05.2022',
        price: 225,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
    ],
  },
  {
    id: 6,
    cost: 216,
    date_order: '2022-05-26',
    products: [
      {
        id: 1,
        name: 'Винегрет овощной',
        date: '24.05.2022',
        price: 230,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
      {
        id: 2,
        name: 'Винегрет овощной',
        date: '23.05.2022',
        price: 225,
        gramm: '220/12',
        calories: '300',
        image: require('./../assets/img/salat.png'),
      },
    ],
  },
];
